[features]
seeds = false
skip-lint = false
[programs.localnet]
calculator = "5PrgSWQ8fh9BaaYVp6Lib2Qhh1FDyt3i9egynn1K6b7e"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/shuridadog/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
